name: keshav_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  country_pickers: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  animated_shimmer: ^1.0.0
#  grouped_buttons:
  grouped_buttons_ns: ^1.0.0
  shimmer_animation: ^2.1.0+1
  shared_preferences:
  connectivity_plus: ^5.0.2
  fluttertoast:
  razorpay_flutter: ^1.3.6
  html:
  package_info:
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.1
  webview_flutter: ^4.2.2
#  url_launcher: ^6.1.11
  persistent_bottom_nav_bar_v2: ^4.2.8
#  carousel_pro:
  sizer: ^2.0.15
  light_modal_bottom_sheet: ^0.0.5
  dio: ^5.1.1
  google_fonts: ^6.1.0
  rounded_loading_button_plus: ^3.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  smartech_base:
  smartech_push:
  smartech_nudges:
  smartech_appinbox:
  video_player: ^2.6.1
  chewie: ^1.5.0
  custom_pop_up_menu: ^1.2.4
  visibility_detector: ^0.4.0+2
  just_audio: ^0.9.33
  url_launcher: ^6.1.11
  flutter_web_browser: ^0.17.1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_appicon0202.png"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
