name: keshav_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.11.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  country_pickers: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  animated_shimmer: ^1.0.0
  grouped_buttons: ^1.0.4
  shimmer_animation: ^2.1.0+1
  shared_preferences:
  connectivity_plus: ^4.0.1
  fluttertoast:
  razorpay_flutter:
  html:
  package_info:
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.1
  url_launcher: ^6.1.12
  persistent_bottom_nav_bar_v2: ^4.2.8
  carousel_pro: ^1.0.0
  sizer: ^2.0.15
  light_modal_bottom_sheet: ^0.0.5
  dio: ^5.1.1
  google_fonts: ^4.0.4
  rounded_loading_button:

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img_appicon0202.png"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
